_wandb:
    value:
        cli_version: 0.23.1
        e:
            g3kj685wgfo9na8t349fgde2f1wh8yk5:
                codePath: FullyConnectedNets.ipynb
                codePathLocal: FullyConnectedNets.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1agI58dBTC1aYYZMsSzXHBpY4kSUZdpBn
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "115658190848"
                        used: "22935506944"
                email: sharestuffhehe@gmail.com
                executable: /usr/bin/python3
                host: ac6c11344865
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: FullyConnectedNets.ipynb
                python: CPython 3.12.12
                root: /content/drive/My Drive/cs231n/assignments/assignment1
                startedAt: "2026-01-20T22:21:57.512143Z"
                writerId: g3kj685wgfo9na8t349fgde2f1wh8yk5
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 1
                - 12
            "12": 0.23.1
            "13": linux-x86_64
layers:
    value:
        - 400
        - 400
        - 400
        - 400
        - 400
learning_rate:
    value: 2.3341106734592843e-05
reg:
    value: 1.0423506650020752e-05
weight_scale:
    value: 0.008229210450111327
