_wandb:
    value:
        cli_version: 0.23.1
        e:
            wo71mf9rwen2366ay8kb68vwii2c9jux:
                codePath: FullyConnectedNets.ipynb
                codePathLocal: FullyConnectedNets.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1agI58dBTC1aYYZMsSzXHBpY4kSUZdpBn
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "115658190848"
                        used: "23076130816"
                email: sharestuffhehe@gmail.com
                executable: /usr/bin/python3
                host: bc0413b720ea
                memory:
                    total: "13605851136"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: FullyConnectedNets.ipynb
                python: CPython 3.12.12
                root: /content/drive/My Drive/cs231n/assignments/assignment1
                startedAt: "2026-01-17T23:12:39.779498Z"
                writerId: wo71mf9rwen2366ay8kb68vwii2c9jux
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 1
                - 12
            "12": 0.23.1
            "13": linux-x86_64
learning_rate:
    value: 0.001
weight_scale:
    value: 0.079
