_wandb:
    value:
        cli_version: 0.23.1
        e:
            8xk07o1uwlzp74ej0dpbrkfk021wgxp8:
                codePath: FullyConnectedNets.ipynb
                codePathLocal: FullyConnectedNets.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1agI58dBTC1aYYZMsSzXHBpY4kSUZdpBn
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "115658190848"
                        used: "22934515712"
                email: sharestuffhehe@gmail.com
                executable: /usr/bin/python3
                host: ac6c11344865
                memory:
                    total: "13605842944"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: FullyConnectedNets.ipynb
                python: CPython 3.12.12
                root: /content/drive/My Drive/cs231n/assignments/assignment1
                startedAt: "2026-01-20T22:19:28.205637Z"
                writerId: 8xk07o1uwlzp74ej0dpbrkfk021wgxp8
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 1
                - 12
            "12": 0.23.1
            "13": linux-x86_64
layers:
    value:
        - 400
        - 400
        - 400
        - 400
        - 400
learning_rate:
    value: 1.0439941476599575e-05
reg:
    value: 0.00014633344701114434
weight_scale:
    value: 0.03163554599814802
